run:
  timeout: 5m

issues:
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec

linters:
  enable:
    - asciicheck
    - errorlint
    - gofmt
    - gosec
    - goimports
    - importas
    - prealloc
    - revive
    - misspell
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace

  disable:
    - errcheck
    - depguard

linters-settings:
  gosec:
    excludes:
      # TODO: Check those example in pkg/caps/caps.go:131
      - G115  # Potential integer overflow when converting between integer types
