version: 1
env:
  - CGO_ENABLED=0

flags:
  - -trimpath

goos: linux
goarch: amd64
main: ./main.go
binary: ko_{{ .Env.VERSION }}_Linux_x86_64
ldflags:
  - "-s -w -X github.com/google/ko/pkg/commands.Version={{ .Env.VERSION }}"
