name: Boilerplate

on:
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@b2555de0cf9724fb9b49d050ff18bd1f49562ba7 # main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
