name: Boilerplate

on:
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@05fbd381f7c158bd33c9bbf3a28f67852269fdf8 # main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
