name: Boilerplate

on:
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@79bd291c02ef97a833226e8da2cefaa775874fd2 # main
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
