name: Do Not Submit

on:
  pull_request:
    branches: ['main']

permissions: {}

jobs:
  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: chainguard-dev/actions/donotsubmit@bed8050123fff65538e2db1902ff9404030c0221 # main
