name: Integration Test

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  test:
    name: Module Tests
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - env:
          GOPATH: does not matter
        run: ./integration_test.sh
