name: Code Style

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  gofmt:
    name: check gofmt
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - uses: chainguard-dev/actions/gofmt@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb
        with:
          args: -s

  goimports:
    name: check goimports
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb

  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - uses: chainguard-dev/actions/trailing-space@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb
        if: ${{ always() }}

      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1.27.0
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: warning
          locale: "US"
          exclude: |
            ./.golangci.yaml

      - uses: get-woke/woke-action-reviewdog@d71fd0115146a01c3181439ce714e21a69d75e31 # v0
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          fail-on-error: true
